// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhpcrrdobnrtktxowkcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocGNycmRvYm5ydGt0eG93a2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDUwNjgsImV4cCI6MjA2ODUyMTA2OH0.HU7zKva1rsjD4WlCIARfAORXzSDpHjujtQ47oELWWII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});